### ISSUE TITLE
General, how long does it take for a training?

### ISSUE THREAD

**Issue by doantientai** [eliahuhorwitz/DeepSIM#2]

**Comment by eliahuhorwitz** [comment]
The main factors are the GPU you are using and the resolution of the training image, in addition, depending on the primitive used for training and the image itself, one may change the number of epochs, 16k is what we found works very well for any image we have tried, that being said, many images did just as well with 8k epochs.
Based on our setup it takes around 2 hours for a 256 image and up to 7 hours for a 1024 image.
Also, note that pix2pixHD is a relatively large architecture. For faster training, it is possible to use a smaller architecture (we’ve had some success with other smaller architectures although the setting was a bit different than this code).

**Comment by doantientai** [comment]
Thanks for you quick respond. I find your idea really interesting. I guess the only drawback is the training time you have to spend for one image before reference. Do you think it is possible to pre-train the network with a bunch of similar images in advance, and we only need to finetune the network on the new image?

**Comment by eliahuhorwitz** [comment]
Your suggestion makes sense, if you try it out please share your results.

**Comment by doantientai** [comment]
Sure, I will keep you updated with my results.
