### ISSUE TITLE
OOM due to unactive loadsize/finesize settings

### ISSUE THREAD

**Issue by eps696** [eliahuhorwitz/DeepSIM#3]
hello, 
i'm trying to run the training on 8gb GPU and facing OOM, whatever load/fine size is set at options (even 64).
could you advise what other options may fix this? 

UPD: this happens only with `face` setup, with `car` the training starts well

**Comment by eliahuhorwitz** [comment]
We are using a pix2pixHD based architecture, their prerequisites require 11GB, you may be able to find a solution at their repository.

**Comment by eliahuhorwitz** [comment]
We are using a pix2pixHD based architecture, their prerequisites require 11GB, you may be able to find a solution at their repository.

**Comment by eps696** [comment]
the requirements obviously depend on the resolution: i have successfully trained 1024x512 model (524288 px) on 8gb card, but 768x768 (589824 px) failed. as far as i can see, the parameters `loadSize` and `fineSize` don't have any effect here; maybe it's worth removing them, or at least mentioning in readme that they don't matter?

**Comment by eps696** [comment]
ok, finally got it:
the option `resize_or_crop` in `base_options.py` is set to `scale_width`, but the options `loadSize` and `fineSize` both are disabled for this specific setting. you may want to change it, so that they act properly, according to your objectives.

**Comment by eliahuhorwitz** [comment]
Thanks, as suggested, the readme and scripts have been updated to avoid confusion.
Keep in mind, in some cases, one may want to set the resize_or_crop set to none as was initially used (in which case the loadSize and fineSize will have no effect), for more details on all the available option you may refer to the pix2pixHD repository where they explain in detail the way these options work.
