### ISSUE TITLE
Train on dataset with several samples

### ISSUE THREAD

**Issue by andorxornot** [eliahuhorwitz/DeepSIM#4]
What do you think i need to change to train with a dataset consisting of several samples?

**Comment by eliahuhorwitz** [comment]
This project does not support multiple images, however, it can be easily modified to support. To train on multiple images you may refer to the original pix2pixHD as our architecture is based on it, in addition, you may find data/base_dataset.py useful. Keep in mind performance may differ as a result of adding additional images.

**Comment by andorxornot** [comment]
thanks!
