### ISSUE TITLE
unrecognized arguments: --online_tps 0

### ISSUE THREAD

**Issue by eps696** [eliahuhorwitz/DeepSIM#5]
happens during test phase. is this obsolete or should be replaced by something else?

also small notes: 
- the option `--resize_or_crop none` repeated twice in training command 
- the option `--no_instance` repeated twice in testing command

**Comment by eliahuhorwitz** [comment]
The flag online_tps was renamed to tps_aug and left in the README by mistake, thanks for bringing it to our attention, the readme and scripts have been updated.
