### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by loretoparisi** [eliahuhorwitz/DeepSIM#7]
Thanks for this amazing project! Any plan to release a pre-trained model?
Thank you in advance.

**Comment by eliahuhorwitz** [comment]
Yes, a few pretained models are coming in the next few weeks

**Comment by loretoparisi** [comment]
@eliahuhorwitz thanks a lot! @shoegazerstella let's have a look then!

**Comment by wardaddy24** [comment]
Hi, Thanks for this amazing work.
Where can I get the pre-trained weights for inference?
